### ISSUE TITLE
error:  workers.api.error.no_access_to_browser_worker [code: 10088]

### ISSUE THREAD

**Issue by feilongproject** [pew/cloudflare-workers-browser-rendering#1]
When I run `npm run deploy`, I receive error: ` workers.api.error.no_access_to_browser_worker [code: 10088]`, maybe I need request this permission, but I not found any link. Can you help me?

**Comment by pew** [comment]
[Workers Browser Rendering](https://blog.cloudflare.com/browser-rendering-open-beta/) is required for that to work
